import type { Metadata } from "next";
import { ReactNode } from "react";
import "@styles/globals.scss";
import { montserrat } from "@app/fonts";

export interface RootLayoutProps {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} flex justify-start items-center`}
      >
        {children}
      </body>
    </html>
  );
}
