import type { Metadata } from "next";
import { ReactNode } from "react";
import "@styles/globals.scss";

export interface RootLayoutProps {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return <html lang="en">{children}</html>;
}
